apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster3
  namespace: namespace1000
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
      # cidrBlocks: ["192.168.0.0/20"]
    pods:
      cidrBlocks: ["192.168.16.0/20"]
      # cidrBlocks: ["192.168.16.0/20"]
    serviceDomain: "cluster.local"
  topology:
    #class: tanzukubernetescluster
    class: builtin-generic-v3.1.0
    version: v1.32.0---vmware.6-fips-vkr.2
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 2
    variables:
      - name:  ntp
        value: "ntp.broadcom.net"
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: management-storage-policy-regular
      - name: defaultStorageClass
        value: management-storage-policy-regular
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "40Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: management-storage-policy-regular
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "4Gi"
          mountPath: "/var/lib/etcd"
          name: etcd
          storageClass: management-storage-policy-regular
